import { motion } from 'framer-motion';
import { FaArrowUp, FaExternalLinkAlt, FaGithub, FaPaw, FaTruck, FaGamepad } from 'react-icons/fa';
import { Button } from '@/components/ui/button';

const projects = [
  { title: 'Loja Pets', label: 'E-commerce', description: 'Loja virtual moderna para o mercado pet, com experiência de compra responsiva, catálogo organizado e interface orientada à conversão.', tags: ['Next.js', 'TypeScript', 'Tailwind CSS'], github: 'https://github.com/LEBEATO/lojapets', demo: 'https://lojapets-coral.vercel.app', icon: <FaPaw />, gradient: 'from-fuchsia-500/30 via-violet-500/15 to-transparent' },
  { title: 'Fortinat Shop', label: 'Plataforma Full Stack', description: 'Experiência inspirada em uma loja de cosméticos de games, com autenticação, inventário, compras, devoluções e persistência de dados.', tags: ['Next.js', 'Prisma', 'PostgreSQL', 'Auth.js'], github: 'https://github.com/LEBEATO/fortinate-shopp', demo: 'https://fortinate-shopp.vercel.app', icon: <FaGamepad />, gradient: 'from-blue-500/30 via-violet-500/15 to-transparent' },
  { title: 'FrotaPro', label: 'Sistema de gestão', description: 'Plataforma empresarial para gestão de frotas, unidades, motoristas, checklists, abastecimentos e manutenção com controle de acesso.', tags: ['Next.js', 'Supabase', 'TypeScript', 'RLS'], github: 'https://github.com/LEBEATO/frotapro', demo: 'https://frotapro-zeta.vercel.app', icon: <FaTruck />, gradient: 'from-violet-500/30 via-purple-500/15 to-transparent' },
];

export default function Projects() {
  return <div className="section-space border-y border-white/[0.06] bg-white/[0.018]"><div className="page-container">
    <div className="mb-12 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div className="max-w-3xl"><p className="mb-3 text-sm font-semibold uppercase tracking-[.22em] text-primary">Projetos em destaque</p><h2 className="text-3xl font-bold tracking-tight sm:text-5xl">Soluções reais, pensadas para pessoas e negócios.</h2></div><a href="https://github.com/LEBEATO" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-semibold text-primary hover:text-violet-300">Ver todos no GitHub <FaArrowUp className="rotate-45" /></a></div>
    <div className="grid gap-6 lg:grid-cols-3">{projects.map((project, index) => <motion.article key={project.title} initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={{ delay: index * .1 }} className="group glass flex min-h-[430px] flex-col overflow-hidden rounded-3xl transition duration-300 hover:-translate-y-2 hover:border-primary/35">
      <div className={`relative flex h-44 items-center justify-center overflow-hidden bg-gradient-to-br ${project.gradient}`}><div className="absolute inset-0 opacity-20 [background-image:linear-gradient(to_right,#fff_1px,transparent_1px),linear-gradient(to_bottom,#fff_1px,transparent_1px)] [background-size:30px_30px]" /><span className="relative grid h-20 w-20 place-items-center rounded-3xl border border-white/15 bg-black/25 text-4xl text-white shadow-2xl backdrop-blur-lg transition duration-300 group-hover:scale-110 group-hover:text-primary">{project.icon}</span><span className="absolute left-5 top-5 rounded-full border border-white/10 bg-black/35 px-3 py-1 text-xs font-semibold text-white/70 backdrop-blur">{project.label}</span></div>
      <div className="flex flex-1 flex-col p-6"><h3 className="text-2xl font-bold">{project.title}</h3><p className="mt-3 flex-1 leading-relaxed text-muted-foreground">{project.description}</p><div className="my-5 flex flex-wrap gap-2">{project.tags.map(tag => <span key={tag} className="rounded-md bg-primary/[0.08] px-2.5 py-1 text-xs font-medium text-violet-200">{tag}</span>)}</div><div className="grid grid-cols-2 gap-3"><Button variant="outline" asChild className="gap-2 border-white/10"><a href={project.github} target="_blank" rel="noreferrer"><FaGithub /> Código</a></Button><Button asChild className="gap-2 bg-primary text-white hover:bg-primary/90"><a href={project.demo} target="_blank" rel="noreferrer"><FaExternalLinkAlt /> Projeto</a></Button></div></div>
    </motion.article>)}</div>
  </div></div>;
}
